### ISSUE TITLE
Question feature improvement

### ISSUE THREAD

**Issue by duykhanh21** [framgia/fepas-qas#18]
- Display question list page.
- Navigate to question detail page when click to a element in list
- Show loading icon while navigation (Nice to have)
- Refactor Question component and actions.

**Comment by yeuem1vannam** [comment]
worth at least 6hrs of implementing

**Comment by duykhanh21** [comment]
6hr x2 (lol)

**Comment by taduyanh** [comment]
Will the question list page have navigation or not ?
If yes, I think 6 hours is good :+1:

**Comment by duykhanh21** [comment]
confirmed - question list page does have navigation.

**Comment by yeuem1vannam** [comment]
Fixed @ #17
